# Generated by Django 4.1.2 on 2022-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_fupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Fupload',
        ),
    ]
