# Generated by Django 4.1.2 on 2022-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_student_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
